### ISSUE TITLE
Anbindung unserer Modelle und Datensätze an LIT

### ISSUE THREAD

**Issue by niklaskorz** [stefanDeveloper/inference#4]
Zur Auswertung sollen unsere Modelle und Datensätze im [Language Interpretability Tool](https://pair-code.github.io/lit/setup/#custom) aufgerufen und inspiziert werden können.
Dazu müssen LITs [Dataset und Model Interfaces](https://pair-code.github.io/lit/setup/#custom) implementiert werden.
Idealerweise können wir mit einer Implementierung alle unsere Modelle und Datensätze abdecken, indem wir für alle Datensätze ein gemeinsames Format verwenden.

Personen: 1

**Comment by bugwelle** [comment]
Links:

- [Adding your own models or data](https://github.com/pair-code/lit#adding-your-own-models-or-data)
- [Adding Models and Data - Guide](https://github.com/PAIR-code/lit/blob/main/documentation/python_api.md#adding-models-and-data)

**Comment by stefanDeveloper** [comment]
Offene Fragen sind:

- in welchem Format befindet sich das Model?
- in welchem Format das Dataset? => CSV

**Comment by bugwelle** [comment]
Weitere Probleme:

https://pair-code.github.io/lit/setup/ => viele Fehler, Beispiele nicht vollständig
https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/simple_tf2_demo.py => braucht (wie alle Beispiele) was von Firebase, ich kriege aber nur einen HTTP 403 Error.

Todo:

1. Eigene Dataset-Klasse schreiben. Orientieren an Beispielen
1. Eigene Model-Klasse schreiben. Orientieren an Beispielen.  Hier fehlt mir aber noch das Wissen, in welchem Format das Model vorhanden ist => Code von Niklas analysieren

**Comment by bugwelle** [comment]
Von #13

<img width="840" alt="Screenshot_20210318_152653" src="https://user-images.githubusercontent.com/1667306/111643761-8011ea00-87ff-11eb-9bc4-67f77bdb63f0.png">
<img width="840" alt="Screenshot_20210318_152704" src="https://user-images.githubusercontent.com/1667306/111643766-80aa8080-87ff-11eb-8640-dd82a388e7e5.png">
<img width="469" alt="Screenshot_20210318_153412" src="https://user-images.githubusercontent.com/1667306/111643769-81431700-87ff-11eb-9a0f-c7639e0bf7c1.png">

**Comment by bugwelle** [comment]
Done.
