### ISSUE TITLE
Code für Evaluation

### ISSUE THREAD

**Issue by niklaskorz** [stefanDeveloper/inference#7]
Der Großteil der Evaluation lässt sich vermutlich in LIT durchführen (siehe #4), jedoch könnte es sein, dass wir bspw. die ROC selbst umsetzen müssen.
Bis wir genau wissen, was mit LIT umsetzbar ist, dient dieses Issue als Platzhalter und Erinnerung.

Personen: 1 oder 2

**Comment by bugwelle** [comment]
ROC steht hier für? :)

**Comment by niklaskorz** [comment]
https://developers.google.com/machine-learning/crash-course/classification/roc-and-auc

**Comment by niklaskorz** [comment]
https://stackoverflow.com/a/38467407
